#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
file_exists(__DIR__ . '/config/local.php') OR die("Local config file not exist\n");

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

$local = require(__DIR__ . '/config/local.php');

if (is_array($local) && isset($local['params'])) {
	if (isset($local['params']['env']) && in_array($local['params']['env'], ['env', 'prod', 'test'])
		&& !defined('YII_ENV')) {
		define('YII_ENV', $local['params']['env']);
	}

	if (isset($local['params']['debug']) && in_array($local['params']['debug'], [true, false])
		&& !defined('YII_DEBUG')) {
		define('YII_DEBUG', $local['params']['debug']);
	}
}
defined('YII_DEBUG') or define('YII_DEBUG', false);
defined('YII_ENV') or define('YII_ENV', 'prod');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/ExtYii.php');

$config = require(__DIR__ . '/config/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
